-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 12:48:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LoginDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LoginDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LoginDB` DEFAULT CHARACTER SET utf8 ;
USE `LoginDB` ;

-- -----------------------------------------------------
-- Table `LoginDB`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LoginDB`.`Login` ;

CREATE TABLE IF NOT EXISTS `LoginDB`.`Login` (
  `user_id` INT(11) NOT NULL,
  `username` VARBINARY(22) NOT NULL,
  `password` VARBINARY(271) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LoginDB`.`Scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LoginDB`.`Scores` ;

CREATE TABLE IF NOT EXISTS `LoginDB`.`Scores` (
  `user_id` INT(11) NOT NULL,
  `ass_id` INT(11) NOT NULL,
  `score` FLOAT NOT NULL,
  PRIMARY KEY (`user_id`, `ass_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



select * FROM login;
insert into LOGIN 	values (1,AES_ENCRYPT("FirstInsert","09b7f4d0752e24acea45"), AES_ENCRYPT("SecondInsert","09b7f4d0752e24acea45"));
select AES_DECRYPT(username, "09b7f4d0752e24acea45") AS username, AES_DECRYPT(`password`, "09b7f4d0752e24acea45") AS pass FROM login;
select AES_DECRYPT(`password`, "09b7f4d0752e24acea45") AS pass FROM login WHERE username = aes_encrypt('FirstInsert', "09b7f4d0752e24acea45");

INSERT INTO login (`username`, `password`) VALUES (AES_ENCRYPT("FirstInsert","09b7f4d0752e24acea45"), AES_ENCRYPT("SecondInsert","09b7f4d0752e24acea45"));
describe login;

drop database logindb;

UPDATE LOGIN SET password = aes_encrypt("TESTING","09b7f4d0752e24acea45") where username = aes_encrypt("316378","09b7f4d0752e24acea45");
DELETE FROM login where username = aes_encrypt("316378","09b7f4d0752e24acea45");